// docs/.vuepress/components/ESLintPlayground.vue
<template>
  <div class="app">
    <sns-bar />
    <div class="main-content">
      <rules-settings
        ref="settings"
        class="rules-settings"
        :rules.sync="rules"
      />
      <div class="editor-content">
        <pg-editor
          v-model="code"
          :rules="rules"
          class="eslint-playground"
          @change="onChange"
        />
        <div class="messages">
          <ol>
            <li
              v-for="(msg, i) in messages"
              :key="msg.line + ':' + msg.column + ':' + msg.ruleId + '@' + i"
              class="message"
              :class="getRule(msg.ruleId).classes"
            >
              [{{ msg.line }}:{{ msg.column }}]: {{ msg.message }} (<a
                :href="getRule(msg.ruleId).url"
                target="_blank"
              >
                {{ msg.ruleId }} </a
              >)
            </li>
          </ol>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import PgEditor from "./components/PgEditor.vue"
import RulesSettings from "./components/RulesSettings.vue"
import SnsBar from "./components/SnsBar.vue"
import { deserializeState, serializeState } from "./state"
import { DEFAULT_RULES_CONFIG, getRule } from "./rules"

const DEFAULT_CODE =
  `<!-- Welcome to @ota-meshi/eslint-plugin-svelte -->
<script>
  let a = 1;
  let b = 2;
  // let c = 2;
  let string = \`this string contains some <strong>HTML!!!</strong>\`;
  let user = {
    firstname: 'Ada',
    lastname: 'Lovelace'
  };
    let current = 'foo';
<` +
  `/script>

<input
  type="number"
  bind:value={a}>
<input
    type="number"
  bind:value={b}>
<input
  type="number"
  bind:value={c}>
<p>{a} + {b} + {c} = {a + b + c}</p>

<p>{@html string}</p>

<input bind:value={user.firstname}>
<input bind:value={user.lastname}>

{@debug user}

<h1>Hello {user.firstname}!</h1>

{#if a}
  <div>foo</div>
{:else if b}
  <div>bar</div>
{:else if b}
  <div>baz</div>
{/if}

<button
  type=button
  class={current === 'foo' ? 'selected' : ''}
  on:click="{() => current = 'foo'}"
>foo</button>
`

export default {
  name: "ESLintPlayground",
  components: { PgEditor, RulesSettings, SnsBar },
  data() {
    const serializedString =
      (typeof window !== "undefined" && window.location.hash.slice(1)) || ""
    const state = deserializeState(serializedString)
    return {
      code: state.code || DEFAULT_CODE,
      rules: state.rules || Object.assign({}, DEFAULT_RULES_CONFIG),
      messages: [],
    }
  },
  computed: {
    serializedString() {
      const defaultCode = DEFAULT_CODE
      const defaultRules = DEFAULT_RULES_CONFIG
      const code = defaultCode === this.code ? undefined : this.code
      const rules = equalsRules(defaultRules, this.rules)
        ? undefined
        : this.rules
      const serializedString = serializeState({
        code,
        rules,
      })
      return serializedString
    },
  },
  watch: {
    serializedString(serializedString) {
      if (typeof window !== "undefined") {
        window.location.replace(`#${serializedString}`)
      }
    },
  },
  mounted() {
    if (typeof window !== "undefined") {
      window.addEventListener("hashchange", this.onUrlHashChange)
    }
  },
  beforeDestroey() {
    if (typeof window !== "undefined") {
      window.removeEventListener("hashchange", this.onUrlHashChange)
    }
  },
  methods: {
    onChange({ messages }) {
      this.messages = messages
    },
    getRule(ruleId) {
      return getRule(ruleId)
    },
    onUrlHashChange() {
      const serializedString =
        (typeof window !== "undefined" && window.location.hash.slice(1)) || ""
      if (serializedString !== this.serializedString) {
        const state = deserializeState(serializedString)
        this.code = state.code || DEFAULT_CODE
        this.rules = state.rules || Object.assign({}, DEFAULT_RULES_CONFIG)
        this.script = state.script
      }
    },
  },
}

function equalsRules(a, b) {
  const akeys = Object.keys(a).filter((k) => a[k] !== "off")
  const bkeys = Object.keys(b).filter((k) => b[k] !== "off")
  if (akeys.length !== bkeys.length) {
    return false
  }

  for (const k of akeys) {
    if (a[k] !== b[k]) {
      return false
    }
  }
  return true
}
</script>
<style scoped>
.main-content {
  display: flex;
  flex-wrap: wrap;
  height: calc(100% - 100px);
  border: 1px solid #cfd4db;
  background-color: #282c34;
  color: #fff;
}

.main-content > .rules-settings {
  height: 100%;
  overflow: auto;
  width: 30%;
  box-sizing: border-box;
}

.main-content > .editor-content {
  height: 100%;
  flex: 1;
  display: flex;
  flex-direction: column;
  border-left: 1px solid #cfd4db;
}

.main-content > .editor-content > .eslint-playground {
  height: 100%;
  width: 100%;
  box-sizing: border-box;
  padding: 3px;
}

.main-content > .editor-content > .messages {
  height: 30%;
  width: 100%;
  overflow: auto;
  box-sizing: border-box;
  border-top: 1px solid #cfd4db;
  padding: 8px;
  font-size: 12px;
}

.eslint-core-rule a {
  color: #8080f2;
}

.eslint-plugin-svelte-rule a {
  color: #40b3ff;
}
</style>

// docs-svelte-kit/src/lib/components/ESLintPlayground.svelte
<script>
  import ESLintEditor from "../eslint/ESLintEditor.svelte"
  import RulesSettings from "../eslint/RulesSettings.svelte"
  import { deserializeState, serializeState } from "../eslint/scripts/state"
  import {
    DEFAULT_RULES_CONFIG,
    getRule,
    createLinter,
    preprocess,
    postprocess,
  } from "../eslint/scripts/linter.js"

  const linter = createLinter()

  const DEFAULT_CODE =
    `<!-- Welcome to @ota-meshi/eslint-plugin-svelte -->
<script>
  let a = 1;
  let b = 2;
  // let c = 2;
  let string = \`this string contains some <strong>HTML!!!</strong>\`;
  let user = {
    firstname: 'Ada',
    lastname: 'Lovelace'
  };
    let current = 'foo';
  let color = 'red';
<` +
    `/script>

<input
  type="number"
  bind:value={a}>
<input
    type="number"
  bind:value={b}>
<input
  type="number"
  bind:value={c}>
<p>{a} + {b} + {c} = {a + b + c}</p>

<p>{@html string}</p>

<input bind:value={user.firstname}>
<input bind:value={user.lastname}>

{@debug user}

<h1>Hello {user.firstname}!</h1>

{#if a}
  <div>foo</div>
{:else if b}
  <div>bar</div>
{:else if b}
  <div>baz</div>
{/if}

<button
  type=button
  class={current === 'foo' ? 'selected' : ''}
  on:click="{() => current = 'foo'}"
>foo</button>

<div style="color: {color};">...</div>
`

  const state = deserializeState(
    (typeof window !== "undefined" && window.location.hash.slice(1)) || "",
  )
  let code = state.code || DEFAULT_CODE
  let rules = state.rules || Object.assign({}, DEFAULT_RULES_CONFIG)
  let messages = []
  let time = ""
  let options = {
    filename: "example.svelte",
    preprocess,
    postprocess,
  }

  $: serializedString = (() => {
    const serializeCode = DEFAULT_CODE === code ? undefined : code
    const serializeRules = equalsRules(DEFAULT_RULES_CONFIG, rules)
      ? undefined
      : rules
    return serializeState({
      code: serializeCode,
      rules: serializeRules,
    })
  })()
  $: {
    if (typeof window !== "undefined") {
      window.location.replace(`#${serializedString}`)
    }
  }
  function onLintedResult(evt) {
    messages = evt.detail.messages
    time = `${evt.detail.time}ms`
  }
  function onUrlHashChange() {
    const newSerializedString =
      (typeof window !== "undefined" && window.location.hash.slice(1)) || ""
    if (newSerializedString !== serializedString) {
      const state = deserializeState(newSerializedString)
      code = state.code || DEFAULT_CODE
      rules = state.rules || Object.assign({}, DEFAULT_RULES_CONFIG)
    }
  }

  /** */
  function equalsRules(a, b) {
    const akeys = Object.keys(a).filter((k) => a[k] !== "off")
    const bkeys = Object.keys(b).filter((k) => b[k] !== "off")
    if (akeys.length !== bkeys.length) {
      return false
    }

    for (const k of akeys) {
      if (a[k] !== b[k]) {
        return false
      }
    }
    return true
  }
</script>

<svelte:window on:hashchange={onUrlHashChange} />

<div class="playground-root">
  <div class="playground-tools">
    <span style="margin-left: 16px">{time}</span>
  </div>
  <div class="playground-content">
    <RulesSettings bind:rules />
    <div class="editor-content">
      <ESLintEditor
        {linter}
        bind:code
        config={{
          parser: "svelte-eslint-parser",
          parserOptions: {
            ecmaVersion: 2020,
            sourceType: "module",
          },
          rules,
          env: {
            browser: true,
            es2021: true,
          },
        }}
        {options}
        on:result={onLintedResult}
      />
      <div class="messages">
        <ol>
          {#each messages as msg, i (`${msg.line}:${msg.column}:${msg.ruleId}@${i}`)}
            <li class="message">
              [{msg.line}:{msg.column}]:
              {msg.message}
              <a
                class="rule-link {getRule(msg.ruleId)?.classes}"
                class:is-rule-error={msg.ruleId}
                href={getRule(msg.ruleId)?.url}
                target="_blank">({msg.ruleId})</a
              >
            </li>
          {/each}
        </ol>
      </div>
    </div>
  </div>
</div>

<style>
  .playground-root {
    height: calc(100vh - 180px);
  }
  .playground-tools {
    height: 24px;
    text-align: end;
  }
  .playground-content {
    display: flex;
    flex-wrap: wrap;
    height: calc(100% - 16px);
    border: 1px solid #cfd4db;
    background-color: #282c34;
    color: #fff;
  }

  .playground-content > .editor-content {
    height: 100%;
    flex: 1;
    display: flex;
    flex-direction: column;
    border-left: 1px solid #cfd4db;
    min-width: 1px;
  }

  .playground-content > .editor-content > .messages {
    height: 30%;
    width: 100%;
    overflow: auto;
    box-sizing: border-box;
    border-top: 1px solid #cfd4db;
    padding: 8px;
    font-size: 12px;
  }
  .playground-content
    > .editor-content
    > .messages
    .rule-link:not(.is-rule-error) {
    display: none;
  }
  .rule-link {
    transition: color 0.2s linear;
  }
  .rule-link.svelte-rule {
    color: #40b3ff80;
  }
  .rule-link.svelte-rule:hover {
    color: #40b3ff;
  }
  .rule-link.core-rule {
    color: #8080f280;
  }
  .rule-link.core-rule:hover {
    color: #8080f2;
  }
</style>
